basket/urls.py
from django.urls import path, include
from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_detail, name='basket_detail'),
    path('add/<int:id>', views.add_to_basket, name='add_to_basket'),
    path('remove/<int:id>', views.remove_from_basket, name='remove_from_basket'),
    path('increase_one_book/<int:id>', views.increase_one_book, name='increase_one_book'),
    path('decrease_one_book/<int:id>', views.decrease_one_book, name='decrease_one_book'),
]

book/urls.py
from django.urls import path
from . import views

app_name = 'book'
urlpatterns = [
    path('', views.all_books, name='home'),
    # path('parent_categories', views.parent_categories, name='parent_categories'),
    path('all_books/', views.all_books, name='all_books'),
    path('details/<int:id>/', views.book_details, name='details'),
    path('categoty/<slug>/<int:id>', views.all_books, name='category'),
    path('search/', views.SearchResultsView.as_view(), name='search'),
    path('create_book/', views.CreateBookView.as_view(), name='create_book'),
    path('edit_book/<int:pk>/', views.EditBookView.as_view(), name='edit_book'),
    path('delete_book/<int:pk>/', views.DeleteBookView.as_view(), name='delete_book'),
    path('create_category/', views.CreateCategoryView.as_view(), name='create_category'),
    path('create_cash_diacount/', views.CreateCashDiscountView.as_view(), name='create_cash_discount'),
    path('create_percent_diacount/', views.CreatePercentDiscountView.as_view(), name='create_percent_discount'),
    path('most_selling_books/', views.most_selling_books, name='most_selling_books'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('book.urls', namespace='book')),
    path('account/', include('account.urls', namespace='account')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('order/', include('order.urls', namespace='order')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('<int:id>/', views.enter_discount_code, name='enter_discount_code'),
    path('create_order/', views.create_order, name='create_order'),
    path('coupon/<int:id>/', views.apply_discount_code, name='coupon'),
    path('create_code_diacount/', views.CreateCodeDiscountView.as_view(), name='create_code_discount'),
]

basket/models.py
from django.db import models
from book.models import *
from account.models import User
from django.forms import ModelForm


# Create your models here.

class Basket(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, verbose_name='کتاب')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='کاربر')
    quantity = models.PositiveIntegerField(verbose_name='تعداد')

    def __str__(self):
        return self.user.email

    class Meta:
        verbose_name = 'سبد خرید'
        verbose_name_plural = 'سبدهای خرید'


class BasketForm(ModelForm):
    class Meta:
        model = Basket
        fields = ['quantity']

basket/views.py
from django.shortcuts import render, redirect
from book.models import Book, Category
from .models import *
from django.contrib.auth.decorators import login_required


# Create your views here.

@login_required(login_url='account:login')  # If the user is not logged in, she will be redirected to the login page
def basket_detail(request):
    baskets = Basket.objects.filter(user_id=request.user.id)
    user = request.user
    total_with_discount = 0
    total_discount_free = 0
    for basket in baskets:
        total_with_discount += basket.quantity * basket.book.final_price
        total_discount_free += basket.quantity * basket.book.unit_price
    parent_categories = Category.objects.filter(is_sub_category=False)
    return render(request, 'basket/basket_details.html', {'baskets': baskets, 'total_with_discount': total_with_discount,
                                                          'total_discount_free': total_discount_free, 'user': user,
                                                          'parent_categories': parent_categories})


@login_required(login_url='account:login')
def add_to_basket(request, id):
    url = request.META.get('HTTP_REFERER')  # for redirecting user to the current page
    if request.method == 'POST':
        form = BasketForm(request.POST)
        if form.is_valid():
            quantity = form.cleaned_data['quantity']
            object = Basket.objects.filter(user_id=request.user.id, book_id=id)
            if object:
                object = Basket.objects.get(user_id=request.user.id, book_id=id)
                object.quantity += quantity
                object.save()
            else:
                Basket.objects.create(book_id=id, user_id=request.user.id, quantity=quantity)
    return redirect('basket:basket_detail')


@login_required(login_url='account:login')
def remove_from_basket(request, id):
    url = request.META.get('HTTP_REFERER')
    Basket.objects.filter(id=id).delete()
    return redirect(url)


@login_required(login_url='account:login')
def increase_one_book(request, id):
    url = request.META.get('HTTP_REFERER')
    basket = Basket.objects.get(id=id)
    book = Book.objects.get(id=basket.book.id)
    if book.inventory > basket.quantity:
        basket.quantity += 1
    basket.save()
    return redirect(url)


@login_required(login_url='account:login')
def decrease_one_book(request, id):
    url = request.META.get('HTTP_REFERER')
    basket = Basket.objects.get(id=id)
    if basket.quantity == 1:
        basket.delete()
    else:
        basket.quantity -= 1
        basket.save()
    return redirect(url)

basket/templates/basket/basket_details.html
{% extends 'base.html' %}
{% block title %}سبد خرید{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <table class="table table-bordered mt-5 border-secondary align-middle m-auto" dir="rtl"
                    style="width: 800px">
              <thead>
                <tr class="text-center">
                  <th scope="col">#</th>
                  <th scope="col">تصویر</th>
                  <th scope="col">نام کتاب</th>
                  <th scope="col">قیمت واحد</th>
                  <th scope="col">تعداد</th>
                  <th scope="col">قیمت کل نهایی</th>
                  <th scope="col">حذف</th>
                </tr>
              </thead>
              <tbody class="text-center">
                  {% for basket in baskets %}
                    <tr>
                      <th scope="row">{{ forloop.counter }}</th>
                      <td><img src="{{ basket.book.image.url }}" style="width: 80px; height: 100px"></td>
                      <td>{{ basket.book.title }}</td>
                      <td>{{ basket.book.unit_price }}</td>
                      <td>
                           <a href="{% url 'basket:increase_one_book' basket.id %}"><i class="fa fa-plus mx-1"></i></a>
                           {{ basket.quantity }}
                           <a href="{% url 'basket:decrease_one_book' basket.id %}"><i class="fa fa-minus mx-1"></i></a>
                      </td>
                      <td>{% widthratio basket.book.final_price 1 basket.quantity %}</td>
                      <td>
                          <a href="{% url 'basket:remove_from_basket' basket.id %}"><i class="fa fa-trash" style="color: red"></i></a>
                      </td>
                    </tr>
                  {% endfor %}
                  <tr>
                      <td colspan="7" style="font-weight: bold; background-color: #EDF1F2">قیمت کل:
                          {{ total_discount_free }}   </td>
                  </tr>
                  {% if total_with_discount != total_discount_free %}
                    <tr>
                      <td colspan="7" style="font-weight: bold; background-color: #EDF1F2; border-top: hidden" >قیمت کل با اعمال تخفیف:
                          {{ total_with_discount }}   </td>
                    </tr>
                  {% endif %}
              </tbody>
            </table>
        </div>
        <div class="text-center my-5">
            <a href="{% url 'order:create_order' %}">
                <button type="submit" class="btn" style="background-color: goldenrod;">ثبت سفارش</button>
            </a>
        </div>
    </div>
{% endblock %}