account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('register/', views.user_register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('change/', views.change_password, name='change'),
    path('active<uidb64>/<token>/', views.RegisterEmail.as_view(), name='active'),
    path('reset/', views.ForgetPassword.as_view(), name='forget_password'),
    path('reset/done', views.MessageSendEmail.as_view(), name='message_send_email'),
    path('confirm/<uidb64>/<token>/', views.ConfirmNewPassword.as_view(), name='password_reset_confirm'),
    path('confirm/done/', views.Complete_new_password.as_view(), name='complete_new_password'),
    path('edit_profile/<int:pk>/', views.EditProfileView.as_view(), name='edit_profile'),
    path('create_address/', views.CreateAddressView.as_view(), name='create_address'),
    path('available_addresses/<int:id>/', views.AvailableAddressesView, name='available_addresses'),
    path('remove_address<int:id>/', views.remove_address_view, name='remove_address'),
    path('edit_address/<int:pk>/', views.EditAddressView.as_view(), name='edit_address'),
    path('history/', views.history_orders, name='history'),
    path('report/', views.Report.as_view(), name='report'),
    path('create_staff/', views.create_staff, name='create_staff'),
]

book/urls.py
from django.urls import path
from . import views

app_name = 'book'
urlpatterns = [
    path('', views.all_books, name='home'),
    # path('parent_categories', views.parent_categories, name='parent_categories'),
    path('all_books/', views.all_books, name='all_books'),
    path('details/<int:id>/', views.book_details, name='details'),
    path('categoty/<slug>/<int:id>', views.all_books, name='category'),
    path('search/', views.SearchResultsView.as_view(), name='search'),
    path('create_book/', views.CreateBookView.as_view(), name='create_book'),
    path('edit_book/<int:pk>/', views.EditBookView.as_view(), name='edit_book'),
    path('delete_book/<int:pk>/', views.DeleteBookView.as_view(), name='delete_book'),
    path('create_category/', views.CreateCategoryView.as_view(), name='create_category'),
    path('create_cash_diacount/', views.CreateCashDiscountView.as_view(), name='create_cash_discount'),
    path('create_percent_diacount/', views.CreatePercentDiscountView.as_view(), name='create_percent_discount'),
    path('most_selling_books/', views.most_selling_books, name='most_selling_books'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('book.urls', namespace='book')),
    path('account/', include('account.urls', namespace='account')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('order/', include('order.urls', namespace='order')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('<int:id>/', views.enter_discount_code, name='enter_discount_code'),
    path('create_order/', views.create_order, name='create_order'),
    path('coupon/<int:id>/', views.apply_discount_code, name='coupon'),
    path('create_code_diacount/', views.CreateCodeDiscountView.as_view(), name='create_code_discount'),
]

order/models.py
from django.db import models
from account.models import User, Address
from book.models import *
from django.forms import ModelForm

# Create your models here.


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, verbose_name='کاربر')
    created = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت سفارش')
    status = models.CharField(max_length=20, default='سفارش', verbose_name='وضعیت')
    address = models.ForeignKey(Address, on_delete=models.DO_NOTHING, null=True, blank=True, verbose_name='آدرس')
    discount = models.PositiveIntegerField(blank=True, null=True, verbose_name='تخفیف')
    # discount=models.ForeignKey(Coupon, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'سفارش'
        verbose_name_plural = 'سفارش ها'

    def __unicode__(self):
        return 'Policy: ' + self.name

    @property
    def total_price(self):
        """
         We use related name for getting all order_items related to this order.
        """
        total = sum(i.final_price() for i in self.order_items.all())
        if self.discount:
            return total - (self.discount / 100) * total
        return total

    def counting_order_items(self):
        order_items = self.order_items.all()
        return sum([order_item.quantity for order_item in order_items])


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='order_items', verbose_name='سفارش')
    book = models.ForeignKey(Book, on_delete=models.CASCADE, verbose_name='کتاب')
    quantity = models.IntegerField(verbose_name='تعداد')
    # user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.order.user.email

    def user(self):
        return self.order.user

    class Meta:
        verbose_name = 'آیتم سفارش'
        verbose_name_plural = 'آیتم های سفارش'

    def final_price(self):
        return self.quantity * self.book.final_price


class Coupon(models.Model):
    code = models.CharField(max_length=100, unique=True, verbose_name='کد تخفیف')
    start_date = models.DateTimeField(verbose_name='تاریخ شروع')
    end_date = models.DateTimeField(verbose_name='تاریخ انقضا')
    discount_percent = models.IntegerField(blank=True, null=True, verbose_name='درصد تخفیف')
    max_discount = models.IntegerField(verbose_name='بیشترین مقدار')

    class Meta:
        verbose_name = 'کوپن'
        verbose_name_plural = 'کوپن ها'

    def __str__(self):
        return f"{self.discount_percent}%"

order/forms.py
from django import forms
from jalali_date.fields import JalaliDateField
from jalali_date.widgets import AdminJalaliDateWidget
from .models import Coupon


class CouponForm(forms.Form):
    code = forms.CharField(max_length=100)


class CreateCodeDiscountForm(forms.ModelForm):
    class Meta:
        model = Coupon
        fields = ('code', 'discount_percent', 'max_discount', 'start_date', 'end_date')

    def __init__(self, *args, **kwargs):
        super(CreateCodeDiscountForm, self).__init__(*args, **kwargs)
        self.fields["start_date"] = JalaliDateField(label=('تاریخ شروع'), widget=AdminJalaliDateWidget)
        self.fields["end_date"] = JalaliDateField(label=('تاریخ پایان'), widget=AdminJalaliDateWidget)

order/views.py
import urllib
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from account.mixins import *
from .models import *
from basket.models import Basket
from django.views.decorators.http import require_POST
from django.contrib import messages
from account.models import Address
from .forms import CouponForm
from book.models import Category
from django.utils import timezone
from .forms import CreateCodeDiscountForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView

# Create your views here.


@login_required
def create_order(request):
    if request.method == "GET":
        addresses = Address.objects.filter(user=request.user)
        parent_categories = Category.objects.filter(is_sub_category=False)
        return render(request, 'order/select_address.html', {'addresses': addresses,
                                                             'parent_categories': parent_categories})
    else:
        # print(request.POST['address_pk'])
        address = Address.objects.get(pk=request.POST['address_pk'])
        order = Order.objects.create(user=request.user, address=address)
        baskets = Basket.objects.filter(user=request.user)
        """
        After creating order, shopping basket of the user will be removed.
        So we store shopping basket's information in the order item model.
        """
        for basket in baskets:
            order_item = OrderItem.objects.create(order_id=order.id, book_id=basket.book_id, quantity=basket.quantity)
            order_item.book.number_of_sell += order_item.quantity
            order_item.save()
        # Remove shopping basket after creating order.
        Basket.objects.filter(user=request.user).delete()
        return redirect('order:enter_discount_code', order.id)


def enter_discount_code(request, id):
    order = Order.objects.get(id=id)
    coupon_form = CouponForm()
    parent_categories = Category.objects.filter(is_sub_category=False)
    return render(request, 'order/enter_discount_code.html', {'order': order, 'coupon_form': coupon_form,
                                                        'parent_categories': parent_categories})


@require_POST
def apply_discount_code(request, id):
    coupon_form = CouponForm(request.POST)
    if coupon_form.is_valid():
        code = coupon_form.cleaned_data['code']
        try:
            coupon = Coupon.objects.get(code__iexact=code, start_date__lte=timezone.now(),
                                        end_date__gte=timezone.now())
        except Coupon.DoesNotExist:
            messages.error(request, 'کد وارد شده نامعتبر است و یا منقضی شده است', 'danger')
            return redirect('order:enter_discount_code', id)
        order = Order.objects.get(id=id)
        order.discount = coupon.discount_percent
        order.save()
    return redirect('order:enter_discount_code', order.id)


class CreateCodeDiscountView(StaffRequiredMixin, LoginRequiredMixin, CreateView):
    model = Coupon
    form_class = CreateCodeDiscountForm
    template_name = 'order/create_code_discount.html'
    success_url = reverse_lazy('book:home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['parent_categories'] = Category.objects.filter(is_sub_category=False)
        return context

order/templates/order/create_code_discount.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load jalali_tags %}
{% block content %}
    <form method="post" dir="rtl" enctype="multipart/form-data">
        {% csrf_token %}
{#        {{ form|crispy}}#}
        <div class="container py-3 mt-4 card" style="background-color:#f6f6f6; width: 380px; height: 490px">
            <h5 class="text-center">افزودن تخفیف کدی</h5>
            <div class="px-5 pt-4 text-center" >
                  <div class="mb-3">
                    {{ form.code|as_crispy_field }}
                  </div>
                  <div class="mb-3">
                    {{ form.discount_percent|as_crispy_field }}
                  </div>
                    <div class=" mb-3">
                    {{ form.max_discount|as_crispy_field }}
                  </div>
                  <div class=" mb-3">
                    {{ form.start_date|as_crispy_field }}
                  </div>
                  <div class="mb-2">
                    {{ form.end_date|as_crispy_field }}
                  </div>
                <div class="text-center my-3">
                    <button type="submit" class="mt-3 btn w-75 text-white m-auto" style="background-color:#395697; width: 200px}
                 border-radius: 5px; ">ذخیره</button>
                </div>
            </div>
        </div>
    </form>
    </div>
{% endblock %}

order/templates/order/enter_discount_code.html
{% extends 'base.html' %}
{% block content %}
    <div class="card m-auto mt-5" style="width: 40rem;">
        <div class="card-body text-center">
            <h5 class="card-title">.کاربر محترم سفارش شما ثبت شد</h5>
            <h6 class="card-subtitle my-4 text-muted">هزینه کل سفارش: {{ order.total_price }}</h6>
            <p class="card-text mt-5">.در صورت داشتن کد تخفیف در قسمت زیر وارد کنید</p>
            <form action="{% url 'order:coupon' order.id %}" method="post" class="mt-4">
                {% csrf_token %}
        {#            {{ coupon_form }}#}
                <input type="text" name="code">
                <button type="submit" class="btn btn-info">اعمال کد تخفیف</button>
            </form>
        </div>
    </div>
{% endblock %}

order/templates/order/select_address.html
{% extends 'base.html' %}
{% block content %}
    <div class="card m-auto my-5" dir="rtl" style="width: 550px">
      <h6 class="card-header text-center">انتخاب آدرس مورد نظر جهت ارسال سفارش</h6>
      <div class="card-body mt-4">
        <form method="post" action="{% url 'order:create_order' %}">
            {% csrf_token %}
            {% if addresses is not None %}
                <select class="form-select" aria-label="Default select example" name="address_pk">
                    {% for address in addresses %}
                        {% if  address.is_default == True %}
                            <option value="{{ address.pk }}" selected>{{ address }}</option>
                        {% endif %}
                    {% endfor %}
                    {% for address in addresses %}
                        {% if  address.is_default == False %}
                           <option value={{ address.pk }}>{{ address }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            {% endif %}
            <div dir="rtl" class="m-auto mt-4" style="font-weight: bold">
                <a href="{% url 'account:create_address' %}" class="text-decoration-none" style="color: #2D8380">
                    <i class="fa fa-plus" aria-hidden="true"></i>
                 افزودن آدرس جدید
                </a>
            </div>
            <div style="text-align: center">
                <button type="submit" class="btn my-5 mr-5" style="width: 150px;
            background-color:goldenrod"> ثبت نهایی سفارش</button>
            </div>
        </form>
      </div>
    </div>
{% endblock %}