account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('register/', views.user_register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('change/', views.change_password, name='change'),
    path('active<uidb64>/<token>/', views.RegisterEmail.as_view(), name='active'),
    path('reset/', views.ForgetPassword.as_view(), name='forget_password'),
    path('reset/done', views.MessageSendEmail.as_view(), name='message_send_email'),
    path('confirm/<uidb64>/<token>/', views.ConfirmNewPassword.as_view(), name='password_reset_confirm'),
    path('confirm/done/', views.Complete_new_password.as_view(), name='complete_new_password'),
    path('edit_profile/<int:pk>/', views.EditProfileView.as_view(), name='edit_profile'),
    path('create_address/', views.CreateAddressView.as_view(), name='create_address'),
    path('available_addresses/<int:id>/', views.AvailableAddressesView, name='available_addresses'),
    path('remove_address<int:id>/', views.remove_address_view, name='remove_address'),
    path('edit_address/<int:pk>/', views.EditAddressView.as_view(), name='edit_address'),
    path('history/', views.history_orders, name='history'),
    path('report/', views.Report.as_view(), name='report'),
    path('create_staff/', views.create_staff, name='create_staff'),
]

basket/urls.py
from django.urls import path, include
from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_detail, name='basket_detail'),
    path('add/<int:id>', views.add_to_basket, name='add_to_basket'),
    path('remove/<int:id>', views.remove_from_basket, name='remove_from_basket'),
    path('increase_one_book/<int:id>', views.increase_one_book, name='increase_one_book'),
    path('decrease_one_book/<int:id>', views.decrease_one_book, name='decrease_one_book'),
]

book/urls.py
from django.urls import path
from . import views

app_name = 'book'
urlpatterns = [
    path('', views.all_books, name='home'),
    # path('parent_categories', views.parent_categories, name='parent_categories'),
    path('all_books/', views.all_books, name='all_books'),
    path('details/<int:id>/', views.book_details, name='details'),
    path('categoty/<slug>/<int:id>', views.all_books, name='category'),
    path('search/', views.SearchResultsView.as_view(), name='search'),
    path('create_book/', views.CreateBookView.as_view(), name='create_book'),
    path('edit_book/<int:pk>/', views.EditBookView.as_view(), name='edit_book'),
    path('delete_book/<int:pk>/', views.DeleteBookView.as_view(), name='delete_book'),
    path('create_category/', views.CreateCategoryView.as_view(), name='create_category'),
    path('create_cash_diacount/', views.CreateCashDiscountView.as_view(), name='create_cash_discount'),
    path('create_percent_diacount/', views.CreatePercentDiscountView.as_view(), name='create_percent_discount'),
    path('most_selling_books/', views.most_selling_books, name='most_selling_books'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('book.urls', namespace='book')),
    path('account/', include('account.urls', namespace='account')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('order/', include('order.urls', namespace='order')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('<int:id>/', views.enter_discount_code, name='enter_discount_code'),
    path('create_order/', views.create_order, name='create_order'),
    path('coupon/<int:id>/', views.apply_discount_code, name='coupon'),
    path('create_code_diacount/', views.CreateCodeDiscountView.as_view(), name='create_code_discount'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}{% endblock %}</title>
        <script src="https://kit.fontawesome.com/d825d4e059.js" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js"></script>
        {% load static %}
        {# for nested dropdown #}
        <link rel="stylesheet" href={% static 'css/style.css' %} >
        <link rel="stylesheet" href="{% static 'admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css' %}">
        <script src="{% static 'admin/js/django_jalali.min.js' %}"></script>
        {# Following script is for showing real time clock #}
        <script type="text/javascript">
            function display_c(){
            var refresh=1000; // Refresh rate in milli seconds
            mytime=setTimeout('display_ct()',refresh)
            }
            function display_ct() {
            var x = new Date().toLocaleTimeString()
            document.getElementById('ct').innerHTML = x;
            display_c();
             }
        </script>
        {% block css %}
        {% endblock %}
    </head>
    <body onload=display_ct();>
        {% include 'navbar.html' %}
        {% include 'messages.html' %}
        {% block content %}
        {% endblock %}
        {# for nested dropdown #}
        <script src="{% static 'js/code.js' %}"></script>

    </body>
</html>

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <h6 {% if message.tags %} class="alert alert-{{ message.tags }}" style="text-align: center">{% endif %}{{ message}}</h6>
    {% endfor %}
{% endif %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="position: sticky; top: 0px;
 height: 70px; z-index: 1">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  <ul class="list-unstyled">
      <li class="text-center pt-2">
          <i class="fa fa-user fa-lg text-white"></i>
          {% if not user.is_authenticated %}
              <div class="container">
                  <div class="row">
                    <a class="nav-link col-2 text-white" href="{% url 'account:login' %}"> ورود</a>
                    <a class="nav-link col-8 text-white ml-2" href="{% url 'account:register' %}">ثبت نام</a>
                  </div>
              </div>
          {% endif %}
          {% if user.is_authenticated and user.is_staff %}
              <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                     data-bs-toggle="dropdown" aria-expanded="falses" style="padding-top: 0px">
                      {{ user.email }}
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <li><a class="dropdown-item" href="{% url 'book:create_book' %}">افزودن کتاب</a></li>
                      <li><a class="dropdown-item" href="{% url 'book:create_category' %}">افزودن دسته بندی</a></li>
                      <li class="nav-item dropdown drop-down02 dropend">
                          <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            افزودن تخفیف
                          </a>
                          <ul class="dropdown-menu sub-menu02" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'book:create_cash_discount' %}">تخفیف نقدی</a></li>
                            <li><a class="dropdown-item" href="{% url 'book:create_percent_discount' %}">تخفیف درصدی</a></li>
                            <li><a class="dropdown-item" href="{% url 'order:create_code_discount' %}">تخفیف کدی</a></li>
                          </ul>
                      </li>
                      {% if user.is_superuser %}
                          <li><a class="dropdown-item" href="{% url 'account:report' %}">گزارش گیری</a></li>
                          <li><a class="dropdown-item" href="{% url 'account:create_staff' %}">تعریف کارمند</a></li>
                      {% endif %}
                      <li><a class="dropdown-item" href="{% url 'account:logout' %}">خروج</a></li>
                  </ul>
              </li>
          {% endif %}
          {% if user.is_authenticated and not user.is_staff %}
              <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                     style="padding-top: 0px" data-bs-toggle="dropdown" aria-expanded="false">
                      {{ user.email }}
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="{% url 'account:edit_profile' user.pk %}">ویرایش پروفایل</a></li>
                    <li><a class="dropdown-item" href="{% url 'account:history' %}">تاریخچه سفارشات</a></li>
                    <li><a class="dropdown-item" href="{% url 'account:logout' %}">خروج</a></li>
                  </ul>
              </li>
          {% endif %}
      </li>
  </ul>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if user.is_authenticated and not user.is_staff %}
          <li class="nav-item">
              <a class="nav-link active mx-3" aria-current="page" href="{% url 'basket:basket_detail' %}">
                  <i class="fa fa-shopping-basket fa-x text-white" aria-hidden="true" ></i>
              </a>
          </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link mx-3"  href="{% url 'book:home' %}">
              <i class="fa fa-home fa-x text-white" ></i>
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle mx-3 text-white"  id="navbarDropdown" role="button" data-bs-toggle="dropdown"
             aria-expanded="false">
              کتابها
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'book:all_books' %}">همه</a></li>
            <li><a class="dropdown-item" href="{% url 'book:most_selling_books' %}">پرفروشترین&zwnj;ها</a></li>
            <li class="nav-item dropdown drop-down02 dropend">
              <a class="nav-link dropdown-toggle text-dark" href="" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                دسته بندی
              </a>
            <ul class="dropdown-menu sub-menu02" aria-labelledby="navbarDropdown">
              {% for parent_category in parent_categories %}
                  {% if not parent_category.categories.all %}
                    <li><a class="dropdown-item" href="{{ parent_category.get_absolute_url }}">{{ parent_category.name }}</a></li>
                  {% else %}
                      <li class="nav-item dropdown drop-down02 dropend">
                          <a class="nav-link dropdown-toggle text-dark" href="{{ obj.get_absolute_url }}"
                             id="navbarDropdown"  data-bs-toggle="dropdown" aria-expanded="false">
                            {{ parent_category.name }}
                          </a>
                          <ul class="dropdown-menu sub-menu02" aria-labelledby="navbarDropdown">
                            {% for sub_category in parent_category.categories.all %}
                                <li><a class="dropdown-item" href="{{ sub_category.get_absolute_url }}">{{ sub_category.name}}</a></li>
                            {% endfor %}
                          </ul>
                      </li>
                  {% endif %}
              {% endfor %}
            </ul>
          </li>
          </ul>
        </li>
      </ul>
      <form  action="{% url 'book:search' %}" method="get" id="navBarSearchForm"
                class=" form-inline float-sm-right" style="width: 400px;">
        <input  class="form-control m-2" onfocus=this.value='' name="input_search" type="text"
                placeholder="جستجو بر اساس نام کتاب یا نویسنده" style="
                border-radius:15px; text-align: center">
      </form>
    </div>
  </div>
</nav>