basket/urls.py
from django.urls import path, include
from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_detail, name='basket_detail'),
    path('add/<int:id>', views.add_to_basket, name='add_to_basket'),
    path('remove/<int:id>', views.remove_from_basket, name='remove_from_basket'),
    path('increase_one_book/<int:id>', views.increase_one_book, name='increase_one_book'),
    path('decrease_one_book/<int:id>', views.decrease_one_book, name='decrease_one_book'),
]

book/urls.py
from django.urls import path
from . import views

app_name = 'book'
urlpatterns = [
    path('', views.all_books, name='home'),
    # path('parent_categories', views.parent_categories, name='parent_categories'),
    path('all_books/', views.all_books, name='all_books'),
    path('details/<int:id>/', views.book_details, name='details'),
    path('categoty/<slug>/<int:id>', views.all_books, name='category'),
    path('search/', views.SearchResultsView.as_view(), name='search'),
    path('create_book/', views.CreateBookView.as_view(), name='create_book'),
    path('edit_book/<int:pk>/', views.EditBookView.as_view(), name='edit_book'),
    path('delete_book/<int:pk>/', views.DeleteBookView.as_view(), name='delete_book'),
    path('create_category/', views.CreateCategoryView.as_view(), name='create_category'),
    path('create_cash_diacount/', views.CreateCashDiscountView.as_view(), name='create_cash_discount'),
    path('create_percent_diacount/', views.CreatePercentDiscountView.as_view(), name='create_percent_discount'),
    path('most_selling_books/', views.most_selling_books, name='most_selling_books'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('book.urls', namespace='book')),
    path('account/', include('account.urls', namespace='account')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('order/', include('order.urls', namespace='order')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book/models.py
from django.db import models

from django.core.validators import MinValueValidator, MaxValueValidator
from django.urls import reverse
from django.utils.text import slugify
from django.db import models
from django.utils import timezone

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=200, verbose_name='نام')
    created = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')
    updated = models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')
    slug = models.SlugField(allow_unicode=True, unique=True, null=True, blank=True, verbose_name='اسلاگ')
    parent_category = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True,
                                        related_name='categories', verbose_name='دسته بندی پدر')
    is_sub_category = models.BooleanField(default=False, verbose_name='زیر دسته')

    class Meta:
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی ها'

    def __str__(self):
        return self.name

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name, allow_unicode=True)
        super(Category, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('book:category', args=[self.slug, self.id])


class PercentDiscount(models.Model):
    percent_amount = models.PositiveIntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(100)], verbose_name='درصد تخفیف')
    max_discount = models.IntegerField(verbose_name='بیشترین مقدار')
    start_date = models.DateTimeField(verbose_name='تاریخ شروع', null=True, blank=True)
    end_date = models.DateTimeField(verbose_name='تاریخ انقضا', null=True, blank=True)

    class Meta:
        verbose_name = 'تخفیف درصدی'
        verbose_name_plural = 'تخفیف های درصدی'

    def __str__(self):
        return f"{self.percent_amount}%"


class CashDiscount(models.Model):
    cash_amount = models.IntegerField(verbose_name='مقدار تخفیف (تومان)')
    start_date = models.DateTimeField(verbose_name='تاریخ شروع', null=True, blank=True)
    end_date = models.DateTimeField(verbose_name='تاریخ انقضا', null=True, blank=True)

    class Meta:
        verbose_name = 'تخفیف نقدی'
        verbose_name_plural = 'تخفیف های نقدی'

    def __str__(self):
        return f" (T) {self.cash_amount} "


class Book(models.Model):
    title = models.CharField(max_length=500, verbose_name='عنوان')
    author = models.CharField(max_length=200, verbose_name='نویسنده')
    inventory = models.PositiveIntegerField(verbose_name='موجودی')
    available = models.BooleanField(default=True, verbose_name='موجود')
    unit_price = models.PositiveIntegerField(verbose_name='قیمت واحد')
    final_price = models.PositiveIntegerField(verbose_name='قیمت نهایی')
    percent_discount = models.ForeignKey(PercentDiscount, on_delete=models.SET_NULL, blank=True, null=True,
                                         verbose_name='تخفیف درصدی')
    cash_discount = models.ForeignKey(CashDiscount, on_delete=models.SET_NULL, blank=True, null=True,
                                      verbose_name='تخفیف نقدی')
    description = models.TextField(blank=True, null=True, verbose_name='توضیحات')
    image = models.ImageField(upload_to='book/', verbose_name='تصویر')
    created = models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')
    updated = models.DateTimeField(auto_now=True, verbose_name='بروزرسانی')
    category = models.ManyToManyField(Category, blank=True, verbose_name='دسته بندی')
    number_of_sell = models.IntegerField(default=0, null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'کتاب'
        verbose_name_plural = 'کتابها'

    @property
    def final_price(self):
        """
        This method returns book's price with applying discount.
        The discount amount resulting the percentage discount should not exceed a certain amount.
        If the amount of the discount exceeds the initial price of the book, the original price
        of the book will be returned.
        """
        now = timezone.now()
        if self.percent_discount:
            cash_discount = (self.percent_discount.percent_amount / 100) * self.unit_price
            if cash_discount > self.percent_discount.max_discount:
                cash_discount = self.percent_discount.max_discount
        if not self.cash_discount and not self.percent_discount:
            return self.unit_price
        if not self.cash_discount and self.percent_discount:
            if self.percent_discount.start_date < now < self.percent_discount.end_date:
                return self.unit_price - cash_discount
        if not self.percent_discount and self.cash_discount:
            if self.cash_discount.start_date < now < self.cash_discount.end_date:
                x = self.unit_price - self.cash_discount.cash_amount
                if x > 0:
                    return x
                else:
                    return self.unit_price
        elif self.percent_discount.start_date < now < self.percent_discount.end_date and \
                self.cash_discount.start_date < now < self.cash_discount.end_date:
            x = self.unit_price - (cash_discount + self.cash_discount.cash_amount)
            if x > 0:
                return x
            else:
                return self.unit_price
        return self.final_price

book/forms.py
from django import forms
from .models import *
from order.models import Coupon
from jalali_date.fields import JalaliDateField
from jalali_date.widgets import AdminJalaliDateWidget


class CreateBookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = '__all__'
        exclude = ['created', 'updated', 'available']


class EditBookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = '__all__'
        exclude = ['created', 'updated', 'available']


class CreateCategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'
        exclude = ['created', 'updated']


class CreateCashDiscountForm(forms.ModelForm):
    class Meta:
        model = CashDiscount
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(CreateCashDiscountForm, self).__init__(*args, **kwargs)
        self.fields["start_date"] = JalaliDateField(label=('تاریخ شروع'), widget=AdminJalaliDateWidget)
        self.fields["end_date"] = JalaliDateField(label=('تاریخ پایان'), widget=AdminJalaliDateWidget)


class CreatePercentDiscountForm(forms.ModelForm):
    class Meta:
        model = PercentDiscount
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(CreatePercentDiscountForm, self).__init__(*args, **kwargs)
        self.fields["start_date"] = JalaliDateField(label=('تاریخ شروع'), widget=AdminJalaliDateWidget)
        self.fields["end_date"] = JalaliDateField(label=('تاریخ پایان'), widget=AdminJalaliDateWidget)

book/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from basket.models import *
from account.mixins import StaffRequiredMixin
from django.views.generic import CreateView, UpdateView, DeleteView
from .forms import *
from django.core.paginator import Paginator

# Create your views here.


def home(request, slug=None, id=None):
    parent_categories = Category.objects.filter(is_sub_category=False)
    return render(request, 'book/home.html', {'parent_categories': parent_categories})


def most_selling_books(request, slug=None, id=None):
    most_selling_books = Book.objects.all().order_by('-number_of_sell')[:3]
    parent_categories = Category.objects.filter(is_sub_category=False)
    return render(request, 'book/most_selling_books.html', {'most_selling_books': most_selling_books,
                                                            'parent_categories': parent_categories})


def all_books(request, slug=None, id=None):
    # The following section is for displaying all books.
    books = Book.objects.all()
    paginator = Paginator(books, 7)
    page_number = request.GET.get('page')
    page_object = paginator.get_page(page_number)  # for pagination.
    parent_categories = Category.objects.filter(is_sub_category=False)
    # The following section is for displaying books of each category.
    if slug and id:
        object = get_object_or_404(Category, slug=slug, id=id)
        books_of_category = Book.objects.filter(category=object)
        paginator = Paginator(books_of_category, 5)
        page_number = request.GET.get('page')
        page_object = paginator.get_page(page_number)
    return render(request, 'book/all_books.html', {'books': page_object, 'parent_categories': parent_categories,
                  'page_number': page_number})


def book_details(request, id):
    book = get_object_or_404(Book, id=id)
    basket_form = BasketForm()
    parent_categories = Category.objects.filter(is_sub_category=False)
    return render(request, 'book/details.html', {'book': book, 'basket_form': basket_form,
                                                 'parent_categories': parent_categories})


class SearchResultsView(ListView):
    template_name = 'book/search_results.html'
    model = Book

    def get_queryset(self):
        # In input tag in base.html we have name='input_search.'
        query = self.request.GET.get('input_search')
        return Book.objects.filter(Q(title__icontains=query) | Q(author__icontains=query))


class CreateBookView(StaffRequiredMixin, LoginRequiredMixin, CreateView):
    model = Book
    form_class = CreateBookForm
    template_name = 'book/create_book.html'
    success_url = reverse_lazy('book:home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['parent_categories'] = Category.objects.filter(is_sub_category=False)
        return context


class EditBookView(StaffRequiredMixin, LoginRequiredMixin, UpdateView):
    model = Book
    form_class = EditBookForm
    template_name = 'book/edit_book.html'
    success_url = reverse_lazy('book:home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['parent_categories'] = Category.objects.filter(is_sub_category=False)
        return context


class DeleteBookView(StaffRequiredMixin, LoginRequiredMixin, DeleteView):
    model = Book
    template_name = 'book/delete_book_confirm.html'
    success_url = reverse_lazy('book:home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['parent_categories'] = Category.objects.filter(is_sub_category=False)
        return context


class CreateCategoryView(StaffRequiredMixin, LoginRequiredMixin, CreateView):
    form_class = CreateCategoryForm
    model = Category
    template_name = 'category/create_category.html'
    success_url = reverse_lazy('book:home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['parent_categories'] = Category.objects.filter(is_sub_category=False)
        return context


class CreateCashDiscountView(StaffRequiredMixin, LoginRequiredMixin, CreateView):
    model = CashDiscount
    form_class = CreateCashDiscountForm
    template_name = 'discount/create_cash_discount.html'
    success_url = reverse_lazy('book:home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['parent_categories'] = Category.objects.filter(is_sub_category=False)
        return context


class CreatePercentDiscountView(StaffRequiredMixin, LoginRequiredMixin, CreateView):
    model = PercentDiscount
    form_class = CreatePercentDiscountForm
    template_name = 'discount/create_percent_discount.html'
    success_url = reverse_lazy('book:home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['parent_categories'] = Category.objects.filter(is_sub_category=False)
        return context

book/templates/book/all_books.html
{% extends 'base.html' %}
{% block title %}کتابها{% endblock %}
{% block content %}
    <div class=" row m-5">
        {% for book in books %}
            <div class="card col-3 my-3" style="width: 11rem; height: 300px; background-color:#E9EDED">
                <div class="  text-center m-auto" dir="rtl">
                    <a class="card-title text-decoration-none" href="{% url 'book:details' book.id %}"
                    style="color:#0073b1; font-weight: bold">
                            <img src="{{ book.image.url }}" class="card-img-top py-0 text-center mb-2" alt="..."
                                 height="200px">
                        {{ book.title|truncatechars:24 }}
                    </a>
                </div>
                {% if book.percent_discount or book.cash_discount %}
                    {% if  book.unit_price != book.final_price %}
                        <span style="text-decoration: line-through" class="text-center text-secondary">
                            {{ book.unit_price }}</span>
                    {% endif %}
                    <span class="text-center text-primary text-secondary fw-bold"> (تومان) {{ book.final_price }}</span>
                {% else %}
                <p class="text-center text-primary text-secondary fw-bold">(تومان) {{ book.unit_price }}  </p>
                {% endif %}
            </div>
        {% endfor %}
        <div class="my-5" aria-label="Page navigation example" >
          <ul class="pagination justify-content-center">
              {% if books.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ books.previous_page_number }}">previous</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ books.previous_page_number }}">{{ books.previous_page_number }}</a>
                </li>
              {% endif %}
              <li class="page-item {% if page_number == page_number %} active {% endif %}">
                  <a class="page-link" href="?page={{ books.number }}">{{ books.number }}</a>
              </li>
              {% if books.has_next %}
                  <li class="page-item">
                    <a class="page-link" href="?page={{ books.next_page_number }}">{{ books.next_page_number }}</a>
                  </li>
                  <li class="page-item">
                    <a class="page-link" href="?page={{ books.next_page_number }}">next</a>
                  </li>
              {% endif %}
          </ul>
        </div>
    </div>
{% endblock %}

book/templates/book/create_book.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
    <link href="{% static 'book/add_book.css' %}" rel="stylesheet">
{% endblock %}
{%load crispy_forms_tags %}
{% block content %}
    <form method="post" dir="rtl" enctype="multipart/form-data">
        {% csrf_token %}
{#        {{ form|crispy}}#}
        <div class="container py-3 mt-4 card" style="background-color:#f6f6f6; width: 500px; height: 720px">
            <h5 class="text-center">افزودن کتاب</h5>
            <div class="px-5 pt-4" >
                <div class="row">
                  <div class=" col-6 mb-2">
                    {{ form.title|as_crispy_field }}
                  </div>
                  <div class=" col-6 mb-2">
                    {{ form.author|as_crispy_field }}
                  </div>
                </div>
                <div class="row">
                  <div class=" col-6 mb-2">
                    {{ form.inventory|as_crispy_field }}
                  </div>
                  <div class=" col-6 mb-2">
                    {{ form.unit_price|as_crispy_field }}
                  </div>
                </div>
                <div class="row">
                  <div class=" col-6 mb-2">
                    {{ form.percent_discount|as_crispy_field }}
                  </div>
                  <div class=" col-6 mb-2">
                    {{ form.cash_discount|as_crispy_field }}
                  </div>
                </div>
                <div class="row">
                  <div class=" col-6 mb-2">
                    {{ form.category|as_crispy_field }}
                  </div>
                  <div class=" col-6 mb-2">
                    {{ form.image|as_crispy_field }}
                  </div>
                </div>
                <div class="row">
                  <div class=" col-3 mb-2">
                    {{ form.description|as_crispy_field }}
                  </div>
                </div>
                <div style="padding-right: 130px">
                    <button type="submit" style="width: 80px" class="mt-3 mb-4">ذخیره</button>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

book/templates/book/delete_book_confirm.html
{% extends 'base.html' %}
{% block content %}
    <div class="card my-5 text-center py-3 m-auto" style="width: 400px; height: 150px ">
        <p> آیا از حذف کردن کتاب {{ book.title }} مطمئن هستید؟</p>
        <div class="m-auto" >
            <form method="post">
                {% csrf_token %}
                <a class="btn btn-info mx-2" href="{% url 'book:details' book.pk %}">خیر</a>
                <button type="submit" class="btn btn-danger">بله</button>
            </form>
        </div>
    </div>
{% endblock %}

book/templates/book/details.html
{% extends 'base.html' %}
{% block title %}جزئیات کتاب{% endblock %}
{% block content %}
    <div class="container py-3 m-auto my-5">
        <div class="row">
            <div class="col-8" dir="rtl">
                <div class="col">
                    <p style="font-weight: bold">کتاب {{ book.title }}</p>
                    <br>
                    {% if book.quantity == 0%}
                        <p class="btn-danger fw-bold" style="width: 100px">موجود نیست</p>
                    {% endif %}
                    <p style="font-weight: bold">مختصری از کتاب:</p>
                    {{ book.description }}
                </div>
                <div class="col my-4">
                    {% if user.is_staff == False %}
                        <form action="{% url 'basket:add_to_basket' book.id %}" method="post">
                            {% csrf_token %}
                             <button type="submit" style="background-color: #395697; border-radius: 5px;
                                margin-left: 5px; font-weight: bold;"
                                class="text-white p-2 btn">افزودن به سبد خرید</button>
                             <input type="number" name="quantity" value="1" min= "1" max="{{ book.inventory }}"
                                required oninvalid="setCustomValidity('حداکثر تعداد انتخابی باید {{ book.inventory }}باشد.')">
                             <br><br>
                        </form>
                    {% endif %}
                    {% if user.is_staff == True %}
                         <a href="{% url 'book:edit_book' book.pk %}" class="btn ml-2" style="background-color: #7DC8C6">ویرایش کتاب</a>
                         <a href="{% url 'book:delete_book' book.pk %}" class="btn btn-danger mx-4">حذف کتاب</a>
                    {% endif %}
                </div>
            </div>
            <div class="col-3" dir="rtl">
                 <img src="{{ book.image.url }}" alt="" style="width: 230px; height: 300px"><br>
            </div>
        </div>
    </div>
{% endblock %}

book/templates/book/edit_book.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
    <link href="{% static 'book/add_book.css' %}" rel="stylesheet">
{% endblock %}
{%load crispy_forms_tags %}
{% block content %}
    <form method="post" dir="rtl">
        {% csrf_token %}
{#        {{ form|crispy}}#}
        <div class="container py-3 mt-4 card " style="background-color:#f6f6f6; width: 500px; height: 770px">
            <h5 class="text-center">ویرایش کتاب</h5>
            <div class="px-5 pt-4" >
                <div class="row">
                  <div class=" col-6 mb-2">
                    {{ form.title|as_crispy_field }}
                  </div>
                  <div class=" col-6 mb-2">
                    {{ form.author|as_crispy_field }}
                  </div>
                </div>
                <div class="row">
                  <div class=" col-6 mb-2">
                    {{ form.inventory|as_crispy_field }}
                  </div>
                  <div class=" col-6 mb-2">
                    {{ form.unit_price|as_crispy_field }}
                  </div>
                </div>
                <div class="row">
                  <div class=" col-6 mb-2">
                    {{ form.percent_discount|as_crispy_field }}
                  </div>
                  <div class=" col-6 mb-2">
                    {{ form.cash_discount|as_crispy_field }}
                  </div>
                </div>
                <div class="row">
                  <div class=" col-6 mb-2">
                    {{ form.category|as_crispy_field }}
                  </div>
                  <div class=" col-6 mb-2">
                    {{ form.image|as_crispy_field }}
                  </div>
                </div>
                <div class="row">
                  <div class=" col-3 mb-2">
                    {{ form.description|as_crispy_field }}
                  </div>
                </div>
                <div style="padding-right: 130px">
                <button type="submit" style="width: 80px" class="mt-3 mb-4">ذخیره</button>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

book/templates/book/home.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block content %}
    <div class="text-center my-5 container">
        <h5>کتاب&zwnj;ها</h5>
        <div class="mt-4">
            <a class="btn m-auto bg-danger text-white" href="{% url 'book:most_selling_books' %}" style="width: 110px">پرفروشترین&zwnj;ها</a>
            <a class="btn m-auto mx-3 bg-danger text-white" href="{% url 'book:all_books' %}" style="width: 110px">همه</a>
        </div>
    </div>
{% endblock %}

book/templates/book/most_selling_books.html
{% extends 'base.html' %}
{% block title %}پرفروش ترینها{% endblock %}
{% block content %}
    <div class=" row m-4">
        {% for book in most_selling_books %}
            <div class="card col-3 my-3" style="width: 11rem; height: 300px; background-color:#E9EDED">
                <div class="  text-center m-auto" dir="rtl">
                    <a class="card-title text-decoration-none" href="{% url 'book:details' book.id %}"
                    style="color:#0073b1; font-weight: bold">

                            <img src="{{ book.image.url }}" class="card-img-top py-0 text-center mb-2" alt="..."
                                 height="200px">
                        {{ book.title|truncatechars:24 }}
                    </a>
                </div>
                {% if book.percent_discount or book.cash_discount %}
                    {% if  book.unit_price != book.final_price %}
                        <span style="text-decoration: line-through" class="text-center text-secondary">
                            {{ book.unit_price }}</span>
                    {% endif %}
                    <span class="text-center text-primary text-secondary"> (تومان) {{ book.final_price }}</span>
                {% else %}
                <p class="text-center text-primary text-secondary">(تومان) {{ book.unit_price }}  </p>
                {% endif %}
            </div>
        {% endfor %}
    </div>
{% endblock %}

book/templates/book/search_results.html
{% extends 'base.html' %}
{% block title%}
    نتایج جستجو
{% endblock %}
{% block content %}
    <div class=" row m-4">
        {% for book in object_list %}
            <div class="card col-3 my-3" style="width: 11rem; height: 300px; background-color:#E9EDED">
                <div class="  text-center m-auto" dir="rtl">
                    <a class="card-title text-decoration-none" href="{% url 'book:details' book.id %}"
                    style="color:#0073b1; font-weight: bold">
                            <img src="{{ book.image.url }}" class="card-img-top py-0 text-center mb-2" alt="..."
                                 height="200px">
                        {{ book.title|truncatechars:24 }}
                    </a>
                </div>
                {% if book.percent_discount or book.cash_discount %}
                    {% if  book.unit_price != book.final_price %}
                        <span style="text-decoration: line-through" class="text-center text-secondary">
                            {{ book.unit_price }}</span>
                    {% endif %}
                    <span class="text-center text-primary text-secondary"> (تومان) {{ book.final_price }}</span>
                {% else %}
                    <p class="text-center text-primary text-secondary">(تومان) {{ book.unit_price }}  </p>
                {% endif %}
            </div>
        {% endfor %}
    </div>
{% endblock %}